### ISSUE TITLE
Linking error when compiling the TorqueTuner ESP-32 firmware due to the new puara module

### ISSUE THREAD

**Issue by Maxw3llGM** [Puara/puara-module#6]
Hi, I believe that the new pushes to the puara module are causing issue, most likely due to the ESP32-S3 specifix fixes that are happening.

Is the code backwards compatible? because I don't see any of the pushes adding #IFDEFS or anything that can support older esp modules. 

I believe the linking error is due to the JTAG pushes.
I also know it's the puara module because when I remove the ifdef for loading the module the compilation of the code works.

![image](https://github.com/Puara/puara-module/assets/87669716/de9c9403-87e9-4fe2-a86e-c29aa1b25d43)

**Comment by Maxw3llGM** [comment]
@aburt2 What do you think I should do?

**Comment by aburt2** [comment]
It's due to the recent pull request, I'll work on fixing it. In the meantime use 
```https://github.com/Puara/puara-module.git#54084c74c275eb061d14798e8a8da7d5d663f94e ```
in the platformio.ini file to pull from the puara-module version before the jtag monitor support was added

**Comment by Maxw3llGM** [comment]
Thanks! it worked!

**Comment by aburt2** [comment]
Wonderful I'll leave this issue open until the underlying issues is solved

**Comment by aburt2** [comment]
Hey @Maxw3llGM  can you try using https://github.com/aburt2/puara-module.git and flash it on an ESP32 and see if that works

**Comment by Maxw3llGM** [comment]
> Hey @Maxw3llGM can you try using https://github.com/aburt2/puara-module.git and flash it on an ESP32 and see if that works

Sure, I'll try it once I get to the lab tmr.

**Comment by aburt2** [comment]
@Maxw3llGM have you had an opportunity to test this?

**Comment by aburt2** [comment]
Fixed in pull request #5
